sigma(13412,'DT','NN').
sigma(11526,'IN','DT').
sigma(9566,'PRP','VBD').
sigma(8865,'NN','IN').
sigma(7159,'JJ','NN').
sigma(6312,'DT','JJ').
sigma(5761,'NN',@).
sigma(4669,@,'PRP').
sigma(4474,'IN','PRP').
sigma(4456,'TO','VB').
sigma(3628,'NN','VBD').
sigma(3522,'VBD','RB').
sigma(3411,'IN','NN').
sigma(3205,'VBD','DT').
sigma(2998,'VBD','IN').
sigma(2912,'NN','NN').
sigma(2839,'PRP','VBP').
sigma(2671,'NN','CC').
sigma(2632,'RB','IN').
sigma(2555,@,'DT').
sigma(2553,'PRP$','NN').
sigma(2472,'NNS','IN').
sigma(2385,'NNP','VBD').
sigma(2260,'RB','JJ').
sigma(2200,'VBD','NNP').
sigma(2183,'JJ','NNS').
sigma(2163,'RB','RB').
sigma(1962,@,'NNP').
sigma(1935,'RB',@).
sigma(1933,'IN','PRP$').
sigma(1918,'DT','NNS').
sigma(1854,'VBD','VBN').
sigma(1845,'NNP','NNP').
sigma(1815,'NN','PRP').
sigma(1797,'VBD','PRP').
sigma(1793,'VB','PRP').
sigma(1766,'NN','RB').
sigma(1719,'VBN','IN').
sigma(1709,'MD','VB').
sigma(1675,'PRP','MD').
sigma(1633,'RB','VB').
sigma(1598,'VB','DT').
sigma(1584,'CC','VBD').
sigma(1550,'JJ','JJ').
sigma(1531,'NNP',@).
sigma(1519,'VB','IN').
sigma(1516,'IN','JJ').
sigma(1468,'RB','VBD').
sigma(1468,'PRP',@).
sigma(1418,'PRP','RB').
sigma(1357,'DT','NNP').
sigma(1339,'JJ','IN').
sigma(1329,@,'RB').
sigma(1302,'VBD','TO').
sigma(1235,'VBG','IN').
sigma(1231,'NNS',@).
sigma(1223,'VBD','VBG').
sigma(1200,'IN','NNP').
sigma(1199,'IN','IN').
sigma(1186,'CC','RB').
sigma(1154,'PRP','IN').
sigma(1137,'RB','VBN').
sigma(1106,'VBD',@).
sigma(1103,@,'IN').
sigma(1076,'JJ',@).
sigma(1050,'RB','PRP').
sigma(1029,'RB','DT').
sigma(1016,'NNS','VBD').
sigma(1002,'JJ','CC').
sigma(983,'VBP','PRP').
sigma(973,'NN','DT').
sigma(930,'IN','NNS').
sigma(913,'PRP$','NNS').
sigma(908,'CC','DT').
sigma(903,'NN','WDT').
sigma(896,'NN','TO').
sigma(869,'CC','PRP').
sigma(853,'TO','DT').
sigma(852,'NNS','CC').
sigma(842,'PRP','VBZ').
sigma(826,'NN','NNS').
sigma(821,'VBD','JJ').
sigma(794,'VBP','RB').
sigma(781,'WDT','VBD').
sigma(772,'NNP','IN').
sigma(771,'VBD','RP').
sigma(761,'PRP$','JJ').
sigma(734,'IN','VBG').
sigma(734,'IN','RB').
sigma(722,'PRP','VB').
sigma(718,'RB','CC').
sigma(711,'DT','RB').
sigma(710,@,'NN').
sigma(702,'RB','VBG').
sigma(700,'MD','RB').
sigma(672,'NN','VBG').
sigma(667,'VBG','DT').
sigma(663,'CC','JJ').
sigma(662,'VB','RB').
sigma(654,'RP','IN').
sigma(652,'VBD','PRP$').
sigma(647,'VBG','TO').
sigma(644,'NNP','NN').
sigma(637,'VBZ','RB').
sigma(635,@,'CC').
sigma(624,'CC','NN').
sigma(623,'NN','VBZ').
sigma(620,'VBG','RB').
sigma(616,'NNP','RB').
sigma(604,'VB','VBN').
sigma(597,'VBZ','DT').
sigma(597,'VBG','NN').
sigma(591,'DT','VBD').
sigma(587,'NN','JJ').
sigma(586,@,'VB').
sigma(582,'CC','IN').
sigma(573,'CD','NNS').
sigma(560,@,'UH').
sigma(550,'VB',@).
sigma(548,'WRB','PRP').
sigma(547,'VBN','TO').
sigma(546,'VB','TO').
sigma(537,'NNP','CC').
sigma(536,'VBD','NN').
sigma(530,'RB','TO').
sigma(528,'NNS','RB').
sigma(524,'VBD','CC').
sigma(515,'JJ','TO').
sigma(498,'PRP','DT').
sigma(465,'WP','VBZ').
sigma(464,'PRP','CC').
sigma(463,'NNP','PRP').
sigma(462,'DT','IN').
sigma(460,'WP','PRP').
sigma(454,'VBN','DT').
sigma(453,'WP','VBD').
sigma(453,'TO','PRP').
sigma(452,'JJ','PRP').
sigma(447,@,'PRP$').
sigma(447,@,'JJ').
sigma(443,'VBN','RB').
sigma(442,'CC','VB').
sigma(433,'VBP','IN').
sigma(427,'IN','CD').
sigma(423,'IN',@).
sigma(421,'VBP','DT').
sigma(417,'VBN',@).
sigma(416,'VB','NN').
sigma(411,'VBZ','IN').
sigma(411,'NNS','PRP').
sigma(400,'VBG','PRP').
sigma(397,'VB','RP').
sigma(393,'EX','VBD').
sigma(388,'VB','JJ').
sigma(382,@,'WP').
sigma(369,'NN','NNP').
sigma(368,'VB','PRP$').
sigma(367,'CD','IN').
sigma(357,'NNS','VBP').
sigma(341,'JJ','RB').
sigma(334,'VBN','NN').
sigma(332,'NN','VBN').
sigma(331,'DT','VBG').
sigma(328,'IN','TO').
sigma(326,'VBN','PRP').
sigma(326,'PDT','DT').
sigma(325,'PRP','PRP').
sigma(324,'NNS','NN').
sigma(322,'RP','DT').
sigma(312,@,'WRB').
sigma(311,'NN','MD').
sigma(310,'PRP','TO').
sigma(308,'DT',@).
sigma(308,'CC','NNP').
sigma(306,'DT','VBZ').
sigma(302,'CC','VBG').
sigma(299,'VBP','VBN').
sigma(299,'JJ','NNP').
sigma(294,'VBG','NNS').
sigma(293,'RB','NN').
sigma(291,'VBP','TO').
sigma(287,'RB','VBP').
sigma(286,'VB','CC').
sigma(283,'VBZ','PRP').
sigma(283,'NNP','DT').
sigma(282,'IN','WDT').
sigma(282,'DT','CD').
sigma(278,'NNS','WDT').
sigma(275,'VBN','VBN').
sigma(266,'VBZ','JJ').
sigma(266,'NN',':').
sigma(265,'NNS','DT').
sigma(265,'NNP','VBG').
sigma(259,'NNS','VBG').
sigma(258,'JJ','VBG').
sigma(257,'JJ','VBD').
sigma(251,'CD','NN').
sigma(247,'VBN','CC').
sigma(247,'TO','PRP$').
sigma(242,'VBG','JJ').
sigma(242,@,'EX').
sigma(241,'VBG',@).
sigma(241,'CC','NNS').
sigma(240,'VBN','RP').
sigma(240,'RP',@).
sigma(233,'TO','NN').
sigma(232,'PRP','RP').
sigma(232,'CC','VBN').
sigma(231,'IN','CC').
sigma(230,'NN','WP').
sigma(228,'VBP',@).
sigma(226,'WDT','PRP').
sigma(219,'VBG','RP').
sigma(216,'PRP','VBG').
sigma(215,'VB','VBG').
sigma(213,'VBG','PRP$').
sigma(210,'WP','VBP').
sigma(207,'VB','VBD').
sigma(206,'MD','PRP').
sigma(202,'CD','CD').
sigma(201,'DT','PRP').
sigma(200,'VB','WP').
sigma(199,'PRP','JJ').
sigma(198,'UH','PRP').
sigma(196,'NN','VB').
sigma(195,'NN','WRB').
sigma(195,'DT','VBN').
sigma(193,'VBN','VBG').
sigma(191,'VBZ','VBN').
sigma(190,'NN','VBP').
sigma(188,'WRB','DT').
sigma(186,':','PRP').
sigma(186,'NNP','NNS').
sigma(185,@,'NNS').
sigma(183,'NNS','JJ').
sigma(180,'NNP','VBZ').
sigma(179,'WDT','VBZ').
sigma(179,'VBN','NNP').
sigma(179,'RB','VBZ').
sigma(179,'NNS','TO').
sigma(178,'DT','JJS').
sigma(175,'TO','NNP').
sigma(175,'NNP','TO').
sigma(172,'RP','RB').
sigma(171,'IN','WP').
sigma(169,'PRP','NN').
sigma(168,'JJ','CD').
sigma(164,'VBD','NNS').
sigma(162,'VBN','JJ').
sigma(162,'JJ','DT').
sigma(160,'NNP','VB').
sigma(159,'VBP','VBG').
sigma(158,@,'WDT').
sigma(154,'RB','WP').
sigma(154,'CD','JJ').
sigma(153,'WP','DT').
sigma(152,'VBZ','NN').
sigma(151,'NNS','VBN').
sigma(146,'VBP','JJ').
sigma(146,'JJ','VBN').
sigma(145,'VBP','NN').
sigma(145,@,'CD').
sigma(142,'NNS','NNS').
sigma(141,'UH','VBD').
sigma(140,'VBG','CC').
sigma(138,'VBD','CD').
sigma(136,'IN','JJS').
sigma(134,'VBZ','VBG').
sigma(133,'NNP','MD').
sigma(130,'VBG','VBN').
sigma(130,'CC','WP').
sigma(129,'WRB','VBZ').
sigma(129,'VB','WRB').
sigma(129,'NN','PRP$').
sigma(128,'VB','NNS').
sigma(127,'CC','PRP$').
sigma(126,'WDT','RB').
sigma(126,'CC','WRB').
sigma(125,'VBP','VBD').
sigma(125,'RB','CD').
sigma(124,'VBZ','TO').
sigma(124,'NNP','NNPS').
sigma(124,'IN','VBN').
sigma(124,'CC','CD').
sigma(122,'WRB','VBP').
sigma(122,'RP','TO').
sigma(122,'PRP$','RB').
sigma(119,'JJR','IN').
sigma(119,'IN','PDT').
sigma(118,'VB','NNP').
sigma(118,'UH',@).
sigma(118,'RBS','JJ').
sigma(118,'RB','NNP').
sigma(116,'VBN','PRP$').
sigma(116,'VBD','VBD').
sigma(116,':','NNP').
sigma(116,'NN','CD').
sigma(116,'IN','EX').
sigma(115,@,'VBG').
sigma(115,'VBD','WP').
sigma(115,'RB','WRB').
sigma(115,'IN','WRB').
sigma(115,'IN','VBD').
sigma(114,'NNP','WP').
sigma(114,'DT','JJR').
sigma(112,'CD','CC').
sigma(112,'CD',@).
sigma(111,':','NN').
sigma(111,'JJS','NN').
sigma(109,'WDT','DT').
sigma(109,'NNS','MD').
sigma(108,'WDT','MD').
sigma(107,'WRB','JJ').
sigma(107,'RBR','JJ').
sigma(107,'NNP','VBP').
sigma(105,'VBN','NNS').
sigma(105,'VBD','WRB').
sigma(105,'UH','RB').
sigma(104,'NNP','JJ').
sigma(103,'WDT','NNP').
sigma(103,'WDT','NN').
sigma(103,'VBP','VB').
sigma(102,@,'VBZ').
sigma(102,'RP','CC').
sigma(102,'DT','DT').
sigma(101,'RP','PRP$').
sigma(100,'PRP','NNP').
sigma(98,'PRP','WP').
sigma(93,'VBZ',@).
sigma(93,'NNS','WP').
sigma(91,'NNPS','NNP').
sigma(91,'JJS','IN').
sigma(91,'JJR','NN').
sigma(89,'DT','RBS').
sigma(88,':','VBD').
sigma(88,'RB','PRP$').
sigma(88,'DT','NNPS').
sigma(87,'DT','VBP').
sigma(85,'VBG','VBD').
sigma(85,'UH','UH').
sigma(83,@,'MD').
sigma(82,'WRB','VBD').
sigma(82,'PRP','VBN').
sigma(82,'CC','VBP').
sigma(81,'RB','RBR').
sigma(80,'VBD','VB').
sigma(79,'VBZ','NNP').
sigma(79,'PRP$','DT').
sigma(78,'VB','VB').
sigma(78,'RB',':').
sigma(78,'PRP','WRB').
sigma(78,':','DT').
sigma(77,'VBZ','WP').
sigma(73,'VBN','VBD').
sigma(73,'JJ','VBZ').
sigma(73,'EX','VBZ').
sigma(72,'PRP$','IN').
sigma(71,'CC','MD').
sigma(70,'WRB','RB').
sigma(70,'NNS','NNP').
sigma(69,'VBP','CC').
sigma(68,'WDT','VBP').
sigma(68,'VBZ','PRP$').
sigma(68,'RB','NNS').
sigma(67,@,'VBP').
sigma(67,'IN',':').
sigma(66,'DT','CC').
sigma(65,'VB','CD').
sigma(65,'RB','JJR').
sigma(65,'NN','UH').
sigma(64,'RB','MD').
sigma(63,'PRP',':').
sigma(63,'NNP',':').
sigma(62,'CD','VBD').
sigma(61,'VBZ','WRB').
sigma(61,@,'VBD').
sigma(61,':','UH').
sigma(60,'VBP','PRP$').
sigma(60,'VBP','NNS').
sigma(60,':','RB').
sigma(60,'PRP$','VBG').
sigma(59,'VBP','WP').
sigma(59,'TO','JJ').
sigma(59,'NNP','WDT').
sigma(59,'MD','VBD').
sigma(59,'CC','VBZ').
sigma(59,'CC',':').
sigma(59,':','CC').
sigma(58,'VBG','NNP').
sigma(58,'NNS',':').
sigma(58,'NNP','WRB').
sigma(57,'NNP','CD').
sigma(57,'DT','RBR').
sigma(57,'CC','EX').
sigma(54,'RB','EX').
sigma(54,'JJR','CC').
sigma(53,'WP','RB').
sigma(53,@,'VBN').
sigma(53,'DT','MD').
sigma(52,'WRB','NNP').
sigma(52,'VBG','VBG').
sigma(52,'VBD','EX').
sigma(52,'PRP$','NNP').
sigma(52,'NN','EX').
sigma(52,'JJ','VBP').
sigma(50,'WP','MD').
sigma(50,'NNP','VBN').
sigma(49,'RBR','RB').
sigma(49,'DT','VB').
sigma(49,'CC','JJR').
sigma(48,'VBP','NNP').
sigma(48,'EX','VBP').
sigma(47,'UH','NNP').
sigma(47,'NN','RP').
sigma(47,'JJS','NNS').
sigma(46,'VBZ','CD').
sigma(46,'PRP','WDT').
sigma(46,'PRP','NNS').
sigma(44,'WP','NN').
sigma(44,'NNS','VBZ').
sigma(44,'JJ','VB').
sigma(44,'JJ','PRP$').
sigma(44,'CD','RB').
sigma(44,@,':').
sigma(43,'WP','IN').
sigma(43,'JJR','NNS').
sigma(43,'CD','TO').
sigma(43,'CC','RBR').
sigma(42,'WRB','TO').
sigma(42,'TO',@).
sigma(42,'NNPS','VBD').
sigma(41,':','VB').
sigma(41,@,'TO').
sigma(41,'RP','NN').
sigma(41,'NN','RBR').
sigma(40,'VB',':').
sigma(40,'TO','NNS').
sigma(40,'PRP','UH').
sigma(39,'RP','VBD').
sigma(39,'NNP','PRP$').
sigma(39,'JJS','JJ').
sigma(39,'CD','PRP').
sigma(38,'VBN','CD').
sigma(38,'JJR',@).
sigma(38,'IN','NNPS').
sigma(37,'TO','CD').
sigma(36,'UH','DT').
sigma(36,'RP','VBG').
sigma(36,'PRP$','VBN').
sigma(36,'NNP','UH').
sigma(36,'DT','WP').
sigma(35,'WP','TO').
sigma(35,'VBP','RP').
sigma(35,'NNS','WRB').
sigma(35,'JJS','PRP').
sigma(35,'DT',':').
sigma(34,'WDT','IN').
sigma(34,'VBZ','VBD').
sigma(34,'TO','VBG').
sigma(34,'JJ','WRB').
sigma(33,'VBZ','CC').
sigma(33,'VBP','WRB').
sigma(33,'JJ',':').
sigma(33,':','JJ').
sigma(33,'IN','VBZ').
sigma(33,'DT','PRP$').
sigma(33,'CC','TO').
sigma(32,'VB','JJR').
sigma(32,'VBD','JJR').
sigma(32,'NNS','VB').
sigma(32,'NNPS',@).
sigma(32,'NN','JJR').
sigma(32,':','IN').
sigma(31,'VBP',':').
sigma(30,'WRB','MD').
sigma(30,'WRB','IN').
sigma(30,'WDT','NNS').
sigma(30,'VBG','WP').
sigma(30,'VBD','VBZ').
sigma(30,'TO','WP').
sigma(30,'MD',@).
sigma(30,'JJR','JJ').
sigma(29,'RP','JJ').
sigma(29,'RBR','IN').
sigma(29,'NNS','PRP$').
sigma(28,'WRB','NN').
sigma(28,'VBG','WRB').
sigma(28,'UH','CC').
sigma(28,'NNPS','IN').
sigma(28,'JJ','WP').
sigma(28,'DT','WDT').
sigma(28,'CD','WDT').
sigma(27,':','WP').
sigma(27,'WDT','JJ').
sigma(27,'VB','WDT').
sigma(27,'VBP','CD').
sigma(27,'VBD','RBR').
sigma(27,'VBD','PDT').
sigma(27,'RBR','CC').
sigma(27,@,'JJS').
sigma(27,'IN','JJR').
sigma(27,'EX','PRP').
sigma(26,'VBZ','VB').
sigma(26,'VBD','UH').
sigma(26,'UH','WP').
sigma(26,'UH','NN').
sigma(26,'UH',':').
sigma(26,'TO','RB').
sigma(26,'MD','VBN').
sigma(26,'MD','IN').
sigma(25,'VB','VBZ').
sigma(25,'VBP','VBZ').
sigma(25,'VB','PDT').
sigma(25,'UH','IN').
sigma(25,'NNS','CD').
sigma(25,'JJR','RB').
sigma(25,'IN','VB').
sigma(25,'EX','MD').
sigma(24,'VBZ',':').
sigma(24,'RP','WRB').
sigma(24,'RP','WP').
sigma(24,'RB','WDT').
sigma(24,'PRP','PRP$').
sigma(24,'PRP$','CC').
sigma(24,'JJS','RB').
sigma(24,'CD',':').
sigma(23,'WRB','PRP$').
sigma(23,'VBN','WRB').
sigma(23,'CD','NNP').
sigma(23,'CD','DT').
sigma(22,'WRB','VBN').
sigma(22,'VBZ','EX').
sigma(22,'RBR',@).
sigma(22,@,'PDT').
sigma(22,'JJ','UH').
sigma(22,'JJ','JJR').
sigma(21,'WP','NNP').
sigma(21,'WDT','PRP$').
sigma(21,'VBZ','RP').
sigma(21,'VBG','CD').
sigma(21,'UH','VB').
sigma(21,'RP','PRP').
sigma(21,'PRP$','CD').
sigma(21,'EX','RB').
sigma(20,'VBD','MD').
sigma(20,'RP','NNP').
sigma(20,'RB','UH').
sigma(20,'NNPS','NN').
sigma(20,'EX','DT').
sigma(19,'TO','IN').
sigma(19,'NNPS','CC').
sigma(19,'JJ','WDT').
sigma(19,'EX','IN').
sigma(19,'DT','TO').
sigma(18,'VBD','VBP').
sigma(18,'VBD',':').
sigma(18,'TO','WRB').
sigma(18,'RBS','RB').
sigma(18,'PRP','EX').
sigma(18,'PRP','CD').
sigma(18,'MD','TO').
sigma(18,'IN','MD').
sigma(18,'DT','RP').
sigma(18,'CD','VBZ').
sigma(18,':','CD').
sigma(17,'VB','RBR').
sigma(17,'VBG','PDT').
sigma(17,'TO','WDT').
sigma(17,'TO',':').
sigma(17,'RP','NNS').
sigma(17,'RBR','NNS').
sigma(17,'RBR','NN').
sigma(17,'PRP$','JJS').
sigma(17,'NNS','RBR').
sigma(17,'NN','PDT').
sigma(17,'CC','WDT').
sigma(16,':','WRB').
sigma(16,'NNPS','RB').
sigma(16,'MD','DT').
sigma(16,'JJ','NNPS').
sigma(16,'IN','VBP').
sigma(16,'EX','CC').
sigma(16,'CD','JJR').
sigma(15,'VBP','VBP').
sigma(15,'VBN','WP').
sigma(15,'VBG','VBZ').
sigma(15,'UH','WDT').
sigma(15,'UH','JJ').
sigma(15,'UH','FW').
sigma(15,'PRP$',@).
sigma(15,':','PRP$').
sigma(15,'NNS','UH').
sigma(15,'NNS','RP').
sigma(15,'MD','NN').
sigma(15,'JJR','TO').
sigma(15,'JJ','MD').
sigma(15,'DT','WRB').
sigma(15,@,@).
sigma(14,'WRB','NNS').
sigma(14,'WP','NNS').
sigma(14,@,'NNPS').
sigma(14,'JJS','CD').
sigma(14,'EX','VBG').
sigma(14,'CD','VBN').
sigma(13,'WP','PRP$').
sigma(13,'VBZ','VBZ').
sigma(13,':','VBZ').
sigma(13,'VB','MD').
sigma(13,'RBR','VB').
sigma(13,'RB','PDT').
sigma(13,'NNPS','VBP').
sigma(13,'MD','CC').
sigma(13,'JJS',@).
sigma(13,'CD','MD').
sigma(12,'WP$','NN').
sigma(12,'VBZ','NNS').
sigma(12,'VBZ','JJR').
sigma(12,'VBN','WDT').
sigma(12,'VBN','VBP').
sigma(12,'VBN','RBR').
sigma(12,'VBN',':').
sigma(12,'TO','CC').
sigma(12,'PRP','PDT').
sigma(12,'JJS','VBD').
sigma(12,'JJR','PRP').
sigma(12,'JJ','JJS').
sigma(12,'IN','UH').
sigma(12,'EX','NN').
sigma(12,'CC','RBS').
sigma(12,'CC','PDT').
sigma(12,':',':').
sigma(11,'WRB',@).
sigma(11,'WP','JJ').
sigma(11,'VBP','EX').
sigma(11,'VBN','MD').
sigma(11,'VBG','WDT').
sigma(11,'VBD','WDT').
sigma(11,'UH','WRB').
sigma(11,'UH','VBP').
sigma(11,'UH','VBN').
sigma(11,'UH','JJR').
sigma(11,'PRP','RBR').
sigma(11,'NN','WP$').
sigma(11,'NNPS','PRP').
sigma(11,'JJS','CC').
sigma(11,@,'JJR').
sigma(11,'DT','EX').
sigma(11,'CC','JJS').
sigma(11,'CC','CC').
sigma(11,'CC',@).
sigma(10,'VB','UH').
sigma(10,'VBP','UH').
sigma(10,'VBN','VBZ').
sigma(10,'VBN','PDT').
sigma(10,':','VBN').
sigma(10,'VBG','JJR').
sigma(10,'VBG',':').
sigma(10,'VB','EX').
sigma(10,'TO','PDT').
sigma(10,'RP','VBN').
sigma(10,'RP','VB').
sigma(10,'RP','CD').
sigma(10,'RBR','VBN').
sigma(10,'RBR','PRP').
sigma(10,@,'RBR').
sigma(10,'RB','JJS').
sigma(10,'JJS','DT').
sigma(10,'EX',@).
sigma(9,'WRB',':').
sigma(9,'WDT','CD').
sigma(9,'VBG','MD').
sigma(9,'VBD','JJS').
sigma(9,'TO','VBD').
sigma(9,'PRP$','VBD').
sigma(9,'PRP$','PRP').
sigma(9,'PDT','PRP$').
sigma(9,':','NNS').
sigma(9,'NNP','EX').
sigma(9,':','MD').
sigma(9,'JJR','VBD').
sigma(9,'DT','UH').
sigma(9,'CD','VBG').
sigma(8,'WRB','WRB').
sigma(8,'WDT','TO').
sigma(8,'VBZ','RBR').
sigma(8,':','VBP').
sigma(8,'VBG','VB').
sigma(8,'VBG','RBR').
sigma(8,'UH','NNS').
sigma(8,'RP','WDT').
sigma(8,'RBR','VBD').
sigma(8,'RBR','DT').
sigma(8,'PRP$','WDT').
sigma(8,'PRP$','JJR').
sigma(8,'NNPS','DT').
sigma(8,'JJR','CD').
sigma(8,'JJ','PDT').
sigma(8,'CD','VBP').
sigma(7,'WRB','EX').
sigma(7,'WRB','CC').
sigma(7,'VBN','VB').
sigma(7,'VBN','JJR').
sigma(7,'VBG','UH').
sigma(7,'PRP$','TO').
sigma(7,'PRP$','RBS').
sigma(7,'PRP','JJR').
sigma(7,'PRP$',':').
sigma(7,'NNS','PDT').
sigma(7,'NNS','JJS').
sigma(7,'NNS','EX').
sigma(7,'NN','JJS').
sigma(7,'MD',':').
sigma(7,'JJS','VB').
sigma(7,'JJ','RBS').
sigma(7,'JJ','EX').
sigma(7,'FW','FW').
sigma(7,'FW',@).
sigma(7,'DT','FW').
sigma(6,'WRB','PDT').
sigma(6,'WP',':').
sigma(6,'WDT','VBG').
sigma(6,'WDT',@).
sigma(6,'WDT',':').
sigma(6,'VBZ','WDT').
sigma(6,'VBZ','PDT').
sigma(6,'VBP','WDT').
sigma(6,'VBP','PDT').
sigma(6,'RP','MD').
sigma(6,'RBS','NNS').
sigma(6,'RBR','VBG').
sigma(6,'PRP','FW').
sigma(6,'NNPS','TO').
sigma(6,'NNPS','JJ').
sigma(6,'NNP','JJS').
sigma(6,'NNP','JJR').
sigma(6,'FW','VBN').
sigma(6,'FW','VB').
sigma(6,'FW','NN').
sigma(5,'WRB','VBG').
sigma(5,'WP','CC').
sigma(5,'WDT','WRB').
sigma(5,'WDT','WDT').
sigma(5,'WDT','UH').
sigma(5,'WDT','JJS').
sigma(5,'WDT','CC').
sigma(5,'VBZ','UH').
sigma(5,'VBZ','RBS').
sigma(5,'VBZ','JJS').
sigma(5,'VB','VBP').
sigma(5,'VBG','VBP').
sigma(5,':','VBG').
sigma(5,'UH','TO').
sigma(5,'UH','PRP$').
sigma(5,'RP','PDT').
sigma(5,'RBR','WDT').
sigma(5,'RB','RP').
sigma(5,'RBR','CD').
sigma(5,'PRP$','VBZ').
sigma(5,'PRP$','RP').
sigma(5,'PRP','RBS').
sigma(5,'NNS','WP$').
sigma(5,'NNS','JJR').
sigma(5,'NNP','PDT').
sigma(5,'MD','WDT').
sigma(5,'MD','NNP').
sigma(5,'JJS','VBN').
sigma(5,'JJS','TO').
sigma(5,'JJS','NNP').
sigma(5,'JJ','RP').
sigma(5,'JJR','DT').
sigma(5,'FW','VBD').
sigma(5,@,'FW').
sigma(5,'CD','WP').
sigma(5,'CD','VB').
sigma(5,'CC','RP').
sigma(4,'WRB','VB').
sigma(4,'WP','VB').
sigma(4,'WP$','NNS').
sigma(4,'WP$','JJ').
sigma(4,'WP',@).
sigma(4,':','WDT').
sigma(4,'VBP','RBS').
sigma(4,'VBP','RBR').
sigma(4,'VBP','JJR').
sigma(4,'VBN','EX').
sigma(4,'UH','MD').
sigma(4,'UH','EX').
sigma(4,'TO','NNPS').
sigma(4,'RP','VBZ').
sigma(4,'RBS','VBD').
sigma(4,'RBR','TO').
sigma(4,'PRP$','WP').
sigma(4,'PRP$','VBP').
sigma(4,'PRP','NNPS').
sigma(4,'NNS','RBS').
sigma(4,'NNS','FW').
sigma(4,'NNPS','WP').
sigma(4,'NNPS','VBG').
sigma(4,'NNPS','MD').
sigma(4,'NN','FW').
sigma(4,'JJS','VBG').
sigma(4,'JJR','VB').
sigma(4,'JJR','RP').
sigma(4,'FW','PRP').
sigma(4,'FW','IN').
sigma(4,'FW','DT').
sigma(4,'EX','WP').
sigma(4,':','EX').
sigma(3,'WRB','WDT').
sigma(3,'WRB','UH').
sigma(3,'WRB','CD').
sigma(3,'WP','WP').
sigma(3,'WP','VBG').
sigma(3,'WP','PDT').
sigma(3,'WP$','JJS').
sigma(3,'WDT','VB').
sigma(3,'WDT','EX').
sigma(3,'VBZ','MD').
sigma(3,'VBN','UH').
sigma(3,'VBN','RBS').
sigma(3,'VBN','NNPS').
sigma(3,'VBN','JJS').
sigma(3,'VBD','RBS').
sigma(3,'VBD','NNPS').
sigma(3,'UH','VBZ').
sigma(3,'SYM','DT').
sigma(3,'RP','RP').
sigma(3,'RBS','VBN').
sigma(3,'RB','NNPS').
sigma(3,'PRP$','WRB').
sigma(3,'PRP$','PRP$').
sigma(3,'PRP$','MD').
sigma(3,'NNP','WP$').
sigma(3,'NNP','RP').
sigma(3,'NNP','RBR').
sigma(3,'MD','MD').
sigma(3,'MD','CD').
sigma(3,'JJS','VBP').
sigma(3,'JJS','RBS').
sigma(3,'JJR','MD').
sigma(3,'JJR',':').
sigma(3,'IN','RBR').
sigma(3,'FW','RB').
sigma(3,'FW','CC').
sigma(3,'EX','TO').
sigma(3,'EX','JJ').
sigma(3,'DT','SYM').
sigma(3,'DT','LS').
sigma(3,':',@).
sigma(2,'WRB','WP').
sigma(2,'WRB','JJR').
sigma(2,'WP','WDT').
sigma(2,'WP','VBN').
sigma(2,'WP','UH').
sigma(2,'WP','JJS').
sigma(2,'WDT','WP').
sigma(2,'WDT','VBN').
sigma(2,'WDT','PDT').
sigma(2,'VBZ','NNPS').
sigma(2,'VBP','JJS').
sigma(2,'VB','JJS').
sigma(2,'VBG','WP$').
sigma(2,'VBD','WP$').
sigma(2,'UH','VBG').
sigma(2,'TO','VBZ').
sigma(2,'SYM','VBZ').
sigma(2,'SYM','NN').
sigma(2,'RP','VBP').
sigma(2,'RP','JJR').
sigma(2,'RP',':').
sigma(2,'RBR','NNP').
sigma(2,'RBR','MD').
sigma(2,'RB','FW').
sigma(2,'PRP$','UH').
sigma(2,'PRP$','EX').
sigma(2,'NN','SYM').
sigma(2,'NN','RBS').
sigma(2,'NNP','SYM').
sigma(2,'NNPS','VB').
sigma(2,'NNPS','NNS').
sigma(2,'NNP','RBS').
sigma(2,'NN','NNPS').
sigma(2,'MD','WRB').
sigma(2,'MD','VBG').
sigma(2,'LS',@).
sigma(2,'JJS','WRB').
sigma(2,'JJS','MD').
sigma(2,'JJS',':').
sigma(2,'JJR','WRB').
sigma(2,'JJR','VBZ').
sigma(2,'JJR','VBN').
sigma(2,'JJ','FW').
sigma(2,'IN','WP$').
sigma(2,'IN','FW').
sigma(2,'FW','NNS').
sigma(2,'FW','JJ').
sigma(2,':','FW').
sigma(2,'EX','WRB').
sigma(2,'EX','WDT').
sigma(2,'EX','NNS').
sigma(2,'EX','EX').
sigma(2,'CD','WRB').
sigma(2,'CD','UH').
sigma(2,'CD','NNPS').
sigma(2,'CC','FW').
sigma(1,'WRB','RBS').
sigma(1,'WRB','JJS').
sigma(1,'WP','WRB').
sigma(1,'WP$','VBG').
sigma(1,'WP$','RB').
sigma(1,'WP$','PRP').
sigma(1,'WP','NNPS').
sigma(1,'WP$','NNPS').
sigma(1,'WP','JJR').
sigma(1,'WP','EX').
sigma(1,'WP$','DT').
sigma(1,'WP','CD').
sigma(1,@,'WP$').
sigma(1,'WDT','RBS').
sigma(1,'WDT','RBR').
sigma(1,'WDT','JJR').
sigma(1,'VBZ','VBP').
sigma(1,'VBZ','SYM').
sigma(1,'VB','RBS').
sigma(1,'VBP','NNPS').
sigma(1,'VBP','MD').
sigma(1,'VB','NNPS').
sigma(1,'VBN','FW').
sigma(1,'VBG','NNPS').
sigma(1,'VB','FW').
sigma(1,'UH','WP$').
sigma(1,'UH','SYM').
sigma(1,'UH','RP').
sigma(1,'TO','VBN').
sigma(1,'TO','TO').
sigma(1,'TO','RP').
sigma(1,'TO','RBR').
sigma(1,'TO','JJR').
sigma(1,'TO','EX').
sigma(1,':','TO').
sigma(1,'SYM','UH').
sigma(1,'SYM','NNP').
sigma(1,'SYM','CC').
sigma(1,'SYM',@).
sigma(1,'RP','UH').
sigma(1,'RP','JJS').
sigma(1,'RP','EX').
sigma(1,'RB','WP$').
sigma(1,'RBS','TO').
sigma(1,'RBS',':').
sigma(1,@,'RBS').
sigma(1,'RBR','WRB').
sigma(1,'RBR','WP').
sigma(1,'RBR','VBZ').
sigma(1,'RBR','RP').
sigma(1,'RBR','JJR').
sigma(1,'RBR','EX').
sigma(1,'RB','RBS').
sigma(1,'PRP','SYM').
sigma(1,'PRP','JJS').
sigma(1,'NNS','NNPS').
sigma(1,'NNPS','WDT').
sigma(1,'NNPS','VBZ').
sigma(1,'NNPS','NNPS').
sigma(1,'NNPS','CD').
sigma(1,':','NNPS').
sigma(1,'NNP','FW').
sigma(1,'MD','WP').
sigma(1,'MD','VBZ').
sigma(1,'MD','RBR').
sigma(1,'MD','PRP$').
sigma(1,'MD','NNS').
sigma(1,'MD','EX').
sigma(1,'LS','DT').
sigma(1,'LS',':').
sigma(1,':','LS').
sigma(1,'JJ','SYM').
sigma(1,'JJS','VBZ').
sigma(1,'JJS','PDT').
sigma(1,':','JJS').
sigma(1,'JJR','WP').
sigma(1,'JJR','VBP').
sigma(1,'JJR','VBG').
sigma(1,'JJR','UH').
sigma(1,'JJR','RBR').
sigma(1,'JJR','PRP$').
sigma(1,'JJR','PDT').
sigma(1,'JJR','NNP').
sigma(1,'JJR','JJR').
sigma(1,'JJR','EX').
sigma(1,'FW','RBR').
sigma(1,'FW','NNP').
sigma(1,'EX','VBN').
sigma(1,'EX','UH').
sigma(1,'EX','PRP$').
sigma(1,'EX','NNP').
sigma(1,'EX','CD').
sigma(1,'CD','RP').
sigma(1,'CD','PRP$').
sigma(1,'CD','PDT').
sigma(1,'CD','JJS').
sigma(1,'CC','UH').
sigma(1,'CC','NNPS').
sigma(1,@,).
